export const languages = [
  { id: '1', name: 'English' },
  { id: '2', name: 'Spanish' },
  { id: '3', name: 'Mandarin' },
  { id: '4', name: 'Hindi' },
  { id: '5', name: 'Arabic' },
  { id: '6', name: 'Russian' },
  { id: '7', name: 'Portuguese' },
  { id: '8', name: 'Bengali' },
  { id: '9', name: 'Japanese' },
  { id: '10', name: 'Punjabi' },
  { id: '11', name: 'German' },
  { id: '12', name: 'French' },
  { id: '13', name: 'Urdu' },
  { id: '14', name: 'Korean' },
  { id: '15', name: 'Italian' },
  { id: '16', name: 'Turkish' },
  { id: '17', name: 'Vietnamese' },
  { id: '18', name: 'Persian' },
  { id: '19', name: 'Polish' },
  { id: '20', name: 'Dutch' },
];
